remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Brandon's Portfolio
description: Questions? Find me on <a href="https://www.linkedin.com/in/brandon-j-chan/">LinkedIn</a> or shoot me an <a href="chan.brandon.j@gmail.com">email</a>.
show_downloads: false
logo: images/portfolio headshot circle.png
