remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Brandon's Portfolio
description: Data science projects with a touch of personality
show_downloads: false
logo: images/portfolio headshot circle.png
